"""Me

Revision ID: 0778d1b9dac6
Revises: ed3e71e8690f
Create Date: 2024-09-24 21:01:21.240513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0778d1b9dac6'
down_revision = 'ed3e71e8690f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_details')
    with op.batch_alter_table('crop_stress_graph_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['result_id'])
        batch_op.create_foreign_key(None, 'result_table', ['result_id'], ['id'])

    with op.batch_alter_table('result_table', schema=None) as batch_op:
        batch_op.drop_constraint('result_table_result_id_fkey', type_='foreignkey')
        batch_op.drop_column('result_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('result_table_result_id_fkey', 'crop_stress_graph_model', ['result_id'], ['id'])

    with op.batch_alter_table('crop_stress_graph_model', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('result_id')

    op.create_table('analysis_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('aoi', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('parameter', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('crop_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='analysis_details_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='analysis_details_pkey')
    )
    # ### end Alembic commands ###
