"""Recreate tables

Revision ID: 0cb585943ea1
Revises: 
Create Date: 2025-02-21 13:33:52.524053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0cb585943ea1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('project_details_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_title', sa.String(length=255), nullable=False),
    sa.Column('project_type', sa.String(length=100), nullable=False),
    sa.Column('starting_date', sa.String(), nullable=False),
    sa.Column('selected_crops', sa.Text(), nullable=False),
    sa.Column('farm_area', sa.String(), nullable=True),
    sa.Column('number_of_farms', sa.Text(), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('geojson', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('selected_parameters', sa.Text(), nullable=False),
    sa.Column('selected_location', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tiff', sa.String(), nullable=False),
    sa.Column('excel', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('tiff_min_max', sa.String(), nullable=True),
    sa.Column('selected_date', sa.String(), nullable=False),
    sa.Column('selected_parameter', sa.Text(), nullable=False),
    sa.Column('geojson', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project_details_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graph_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_farm_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('geojson', sa.JSON(), nullable=False),
    sa.Column('selected_date', sa.String(), nullable=False),
    sa.Column('selected_parameter', sa.Text(), nullable=False),
    sa.Column('result_details', sa.String(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['result_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('graph_table')
    op.drop_table('result_table')
    op.drop_table('project_details_table')
    op.drop_table('user_table')
    # ### end Alembic commands ###
