"""Added ProcessDetails Table

Revision ID: 324a2774fc58
Revises: 48a2c6b57b42
Create Date: 2024-09-24 11:12:15.036823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324a2774fc58'
down_revision = '48a2c6b57b42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('process_date', sa.String(), nullable=False),
    sa.Column('selected_date', sa.String(), nullable=False),
    sa.Column('selected_parameter', sa.Text(), nullable=False),
    sa.Column('tiff_file_path', sa.String(), nullable=False),
    sa.Column('excel_file_path', sa.String(), nullable=False),
    sa.Column('unique_farm_ids', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crop_stress_graph_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('process_id', sa.Integer(), nullable=False))  # Make process_id nullable
        batch_op.create_foreign_key(None, 'process_details', ['process_id'], ['id'])

    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crop_stress_graph_model', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('process_id')

    op.drop_table('process_details')
    # ### end Alembic commands ###
