"""Added FarmResults Table

Revision ID: 4744cf0ee56e
Revises: e04d0c56c088
Create Date: 2024-09-12 12:28:08.607216

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4744cf0ee56e'
down_revision = 'e04d0c56c088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_stress_graph_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('geojson', sa.JSON(), nullable=False),
    sa.Column('selected_date', sa.String(), nullable=False),
    sa.Column('selected_parameter', sa.Text(), nullable=False),
    sa.Column('result_details', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('farm_result')
    op.drop_table('farm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('farm_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('geojson', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='farm_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='farm_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('farm_result',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('farm_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parameter', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('result', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('date_selected', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], name='farm_result_farm_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='farm_result_pkey')
    )
    op.drop_table('crop_stress_graph_model')
    # ### end Alembic commands ###
