"""Added FarmResults Table

Revision ID: 48a2c6b57b42
Revises: 4744cf0ee56e
Create Date: 2024-09-17 15:54:51.449763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a2c6b57b42'
down_revision = '4744cf0ee56e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crop_stress_graph_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_farm_id', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crop_stress_graph_model', schema=None) as batch_op:
        batch_op.drop_column('unique_farm_id')

    # ### end Alembic commands ###
