"""Initial migration after resetting database

Revision ID: 4bff404277be
Revises: 
Create Date: 2024-08-12 13:56:21.772039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bff404277be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_details', schema=None) as batch_op:
        # Commenting out the line that drops the non-existent column
        # batch_op.drop_column('details')
         pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
