"""asleee

Revision ID: 4ca64ce946f9
Revises: a2dab87a458e
Create Date: 2024-09-25 13:34:13.397975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca64ce946f9'
down_revision = 'a2dab87a458e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_max', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result_table', schema=None) as batch_op:
        batch_op.drop_column('min_max')

    # ### end Alembic commands ###
