"""Fresh start

Revision ID: 4d732acfaf64
Revises: 
Create Date: 2025-04-01 00:27:07.011567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d732acfaf64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graph_table', schema=None) as batch_op:
        batch_op.alter_column('inference',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('result_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result_table', schema=None) as batch_op:
        batch_op.drop_column('client_active')

    with op.batch_alter_table('graph_table', schema=None) as batch_op:
        batch_op.alter_column('inference',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
