"""Added redsi min max

Revision ID: 565c1c337db3
Revises: e28bec8da73f
Create Date: 2024-10-02 14:04:25.938407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '565c1c337db3'
down_revision = 'e28bec8da73f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tiff_min_max', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('redsi_min_max', sa.String(), nullable=True))
        batch_op.drop_column('min_max')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_max', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('redsi_min_max')
        batch_op.drop_column('tiff_min_max')

    # ### end Alembic commands ###
