"""Added AnalysisDetails Table

Revision ID: 5bfdd1dc239b
Revises: 4bff404277be
Create Date: 2024-08-20 15:14:27.384751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5bfdd1dc239b'
down_revision = '4bff404277be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('analysis_details',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('user_id', sa.Integer(), nullable=False),
    # sa.Column('aoi', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    # sa.Column('parameter', sa.Text(), nullable=False),
    # sa.Column('crop_type', sa.Text(), nullable=False),
    # sa.Column('date', sa.String(), nullable=False),
    # sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_details')
    # ### end Alembic commands ###
