"""asle

Revision ID: a2dab87a458e
Revises: 0778d1b9dac6
Create Date: 2024-09-25 10:01:03.365617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2dab87a458e'
down_revision = '0778d1b9dac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crop_stress_graph_model', schema=None) as batch_op:
        batch_op.drop_constraint('crop_stress_graph_model_result_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crop_stress_graph_model', schema=None) as batch_op:
        batch_op.create_unique_constraint('crop_stress_graph_model_result_id_key', ['result_id'])

    # ### end Alembic commands ###
