"""Added date, geojson, parameter to resulttable

Revision ID: af16fbbc3557
Revises: 4ca64ce946f9
Create Date: 2024-09-25 15:07:05.708092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af16fbbc3557'
down_revision = '4ca64ce946f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_date', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('selected_parameter', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('geojson', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result_table', schema=None) as batch_op:
        batch_op.drop_column('geojson')
        batch_op.drop_column('selected_parameter')
        batch_op.drop_column('selected_date')

    # ### end Alembic commands ###
