"""Added date, geojson, parameter to resulttable

Revision ID: e28bec8da73f
Revises: af16fbbc3557
Create Date: 2024-09-25 15:09:51.683704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e28bec8da73f'
down_revision = 'af16fbbc3557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result_table', schema=None) as batch_op:
        batch_op.alter_column('selected_date',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('selected_parameter',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('geojson',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result_table', schema=None) as batch_op:
        batch_op.alter_column('geojson',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('selected_parameter',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('selected_date',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
